roeniss/dhlottery-api

- README.md
> fix: CONTRIBUTING.md path

- README.md
- docs/CONTRIBUTING.md
- resolves #19 
- 3.8 미만 버전에서도 여전히 **설치가 된다.** 마지막으로 지원하는 1.3.1 버전으로... 그래서 3.8 을 권장하는 문구를 리드미에 추가함.
> contributing, readme 개선

- src/dhapi/purchase/lotto645_controller.py
- resolves #17 
이번주 구매를 다 해서... 다음주에 한장씩 사면서 확인해봐야 됨
> 구매 결과 창에서 모드 설명 추가

- src/dhapi/purchase/lotto645_controller.py
> fix mode 설명 파이썬 버그 

- requirements.txt
- src/dhapi/purchase/lotto645_controller.py
- src/dhapi/router/arg_parser.py
- src/dhapi/router/router.py
- src/dhapi/router/version_checker.py
- resolves #16 
- resolves #15
changelogs 를 보여주는건 조금 손이 많이 갈 듯 하여 우선 보류함
> 신버전 나왔을 때 업그레이드

- .pylintrc
- README.md
- src/dhapi/domain_object/lotto645_buy_request.py
- src/dhapi/router/arg_parser.py
> 파라미터 변경 (`*` -> `x`, `-p` for 프로필 파일)

- .pylintrc
- Makefile
- src/dhapi/client/lottery_client.py
- src/dhapi/configuration/logger.py
- src/dhapi/domain_object/lotto645_buy_request.py
- src/dhapi/purchase/lotto645_controller.py
- src/dhapi/router/arg_parser.py
- src/dhapi/router/router.py
- resolves #10 
- `-d/--debug` 옵션을 추가. 이 옵션을 활성화하면 전체 응답이 보이도록 logging 을 추가했다. 
- 반자동 판별 로직에 버그가 있었다. 이를 수정함.
> Global exception handler

- src/dhapi/client/lottery_client.py
- src/dhapi/domain_object/lotto645_buy_request.py
- src/dhapi/purchase/lotto645_controller.py
- src/dhapi/router/arg_parser.py
resolves #32
* Rename 'half-auto' keyword to 'semi-auto'.
* Semi-auto and manual modes work fine.
* Change -g,--game value format:
- manual mode: -g 1,2,3,4,5,6
- semi-auto mode (two automatic numbers): -g 1,2,3,4
- auto mode: -g auto
> Implement semi-auto and manual modes

- docs/CONTRIBUTING.md
- src/dhapi/client/lottery_client.py
- src/dhapi/router/arg_parser.py
#47 
---
refs: https://github.com/techinpark/lottery-bot/pull/2/files
여러분 제가 고쳤어요! (베끼긴했지만..)
---
cc: @roeniss
> (#47) fix: direct INTCOM1, INTCOM2

- README.md
- requirements.txt
- src/dhapi/router/arg_parser.py
- #44 
```shell
cat ~/.dhapi/credentials    
[default]
username = seunggabi
password = ***********
[test]
username = asdf
password = 1234
```
```shell
PYTHONPATH=./src/ python3 src/dhapi/main.py buy_lotto645 -q  
[Lotto645 Buy Request]
Game A: []
Game B: []
Game C: []
Game D: []
Game E: []
❓ 위와 같이 구매하시겠습니까? [Y/n] yes
✅ --quiet 플래그가 주어져 자동으로 구매를 진행합니다.
2023-05-31 21:47:34 [error    ] 🚨 에러가 발생했습니다: 구매에 실패했습니다: [온라인복권 주간 구매한도] 초과되었습니다.
🚨 에러가 발생했습니다: 구매에 실패했습니다: [온라인복권 주간 구매한도] 초과되었습니다.
PYTHONPATH=./src/ python3 src/dhapi/main.py buy_lotto645 -q -p qwer
2023-05-31 21:47:38 [error    ] 🚨 에러가 발생했습니다: 로그인에 실패했습니다. 아이디 또는 비밀번호를 확인해주세요.
🚨 에러가 발생했습니다: 로그인에 실패했습니다. 아이디 또는 비밀번호를 확인해주세요.
```
> (#44) feat: profile added

- .github/workflows/lintfmt.yml
> Create lintfmt.yml #37

- README.md
value를 저장할 시 쌍따옴표를 추가함으로써 사용자 경험을 개선하였습니다.
우선 문서작업으로만 개선한 뒤, 추후 작업을 통해 리팩토링을 통한 개선까지도 작업해보겠습니다.
> (#64) docs: user credential snippet 개선

- .pylintrc
- resolves https://github.com/roeniss/dhlottery-api/issues/66
> feat(pylint): Remove rule W0707 (raise-missing-from)

- requirements.txt
- src/dhapi/router/credentials_provider.py
> 계정정보 입력기능 추가

- README.md
- src/dhapi/router/arg_parser.py
많은 부분이 리드미 없이도 진행이 가능한 상태가 되었다고 판단하여, README 를 대폭 감소시켰습니다.
> docs: README 간소화

- README.md
- requirements.txt
- src/dhapi/client/lottery_client.py
- src/dhapi/client/mailjet_email_client.py
- src/dhapi/purchase/lotto645_controller.py
- src/dhapi/router/arg_parser.py
- src/dhapi/router/router.py
- src/dhapi/user_info/user_info_controller.py
- tests/test_arg_parser.py
- tests/test_mailjet_email_client.py
- resolves https://github.com/roeniss/dhlottery-api/issues/56
> feat: Email 정보 입력 기능 추가

- .github/workflows/tag-and-publish.yml
불필요하게 호출되고 있더라.. https://github.com/roeniss/dhlottery-api/actions/runs/7873158441
> refactor: 수동으로 배포 workflow 실행하도록 변경

- README.md
- resolves https://github.com/roeniss/dhlottery-api/issues/79
> docs: Pypi package badge on Readme

- requirements.txt
- src/dhapi/client/lottery_client.py
- src/dhapi/purchase/lotto645_controller.py
- src/dhapi/router/arg_parser.py
- src/dhapi/router/router.py
- resolves https://github.com/roeniss/dhlottery-api/issues/41
> feat: 가상계좌 입금 신청 API

- requirements.txt
> fix(deps): Fix click version to 8.1.8

- src/dhapi/port/lottery_client.py
- resolved https://github.com/roeniss/dhlottery-api/issues/129
> fix: assign-virtual-account failure
